spring:
  jpa:
    hibernate:
      ddl-auto: ${ISI_DDL_AUTO:update}
groupeisi:
  gl:
    responsable:
      prenom: ${RESPONSABLE_PRENOM:claye}
      nom: ${RESPONSABLE_NOM:Ndiaye}
      email: ${RESPONSABLE_EMAIL:clayendaye@groupeisi.com}
